package task1;

public class Program {
    /**
     *
     * Данная конструкция try-catch не требует никаких изменений.
     * Деление на 0 происходит внутри блока "try", поэтому исключение будет
     * поймано.

    try {
        int d = 0;
        double catchedRes1 = intArray[8] / d;
        System.out.println("catchedRes1 = " + catchedRes1);
    } catch (ArithmeticException e) {
        System.out.println("Catching exception: " + e);
    }

    */
}
